### ISSUE TITLE
syntax of update

### ISSUE THREAD

**Issue by marcstein** [kimvex/mongodb-crystal#10]
Hi,

I'm trying to implement the following:

  quote = env.params.query["quote"]
  status = env.params.query["status"]
  collection.update(quote: "#{quote}", status: "#{status}")

Essentially, query for a record with a specific value for quote and update the value stored in status. A unique index exists on quote, so we don't have to deal with multiple updates.

Can you suggest what the correct syntax would be in this case?

Many thanks in advance!

Marc

**Comment by kimvex** [comment]
Hi, you could add it as follows:

```
collection.update({"quote" => "#{quote}"}, {"status" => "#{status}"}, LibMongoC::UpdateFlags::NONE, nil)
```

If you did not resolve your question or have other questions, tell me to help you. Greetings.

**Comment by marcstein** [comment]
Thanks so much for the reply! Unfortunately, when I run this I get the
following compiler error:

Fundtap_data.update({"quote" => "#{quote}"}, {"status" => "#{status}"},
LibMongoC::UpdateFlags::NONE, nil)
                    ^-----
Error: undefined method 'update' for Fundtap_data.class

Fundtap_data being the collection name and linked by

class Fundtap_data < Mongo::ORM::Document
  field quote : String
  field ap_total_current_month : String
....
end

Any thoughts?

Thanks!

Marc

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by kimvex** [comment]
I understand, you are using MongoORM. Which uses the save method that if there is `_id` in the document that you are passing in the method, it updates it if not, it creates it. Here what you can do is the form that the documentation of MongoORM tells you to be able to save a new document. For example:

This creates the document:
```
user = User.new
user.name = "Sam"
user.age = 248
user.turned_on = true
user.save
```

This updates the document
```
user = User.new
user._id = "5d585eebfef58306e831a032"
user.name = "Samuel"
user.age = 450
user.turned_on = true
user.save
```

[https://github.com/sam0x17/mongo_orm/blob/master/src/mongo_orm/persistence.cr#L7](https://github.com/sam0x17/mongo_orm/blob/master/src/mongo_orm/persistence.cr#L7)

Do not hesitate to ask me anything.

**Comment by marcstein** [comment]
Thanks!
