### ISSUE TITLE
To Update the basics to 1.15

### ISSUE THREAD

**Issue by washu** [kimvex/mongodb-crystal#2]
# mongo monkey patch
require "mongo"
# add to lib_mongo.cr
  fun mongo_init = mongoc_init (Void*)
  fun mongo_cleanup = mongoc_cleanup (Void*)
# add to mongo module after set log handler
LibMongoC.mongo_init(nil)
at_exit { LibMongoC.mongo_cleanup(nil) }

**Comment by kimvex** [comment]
@washu Thank you for your support and interest in helping to improve the library. This afternoon the changes you mention will be added.

**Comment by kimvex** [comment]
In this commit the change was added [Commit](https://github.com/kimvex/mongodb-crystal/commit/713c58889881b5551055b31d2df021c0b039b89f) @washu
